version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: epayco_server
    ports:
      - "8080:80"
    # Monta el c贸digo, pero preserva vendor con volumen an贸nimo
    volumes:
      - ./server:/var/www/html
      - /var/www/html/vendor
      - ./server/docker/nginx.conf:/etc/nginx/http.d/default.conf:ro
      - ./server/docker/supervisord.conf:/etc/supervisord.conf:ro
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: epayco_db
      DB_USERNAME: user
      DB_PASSWORD: password
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: "587"
      MAIL_USERNAME: perproject2@gmail.com
      MAIL_PASSWORD: ndmipkhbxbndafwh
      MAIL_ENCRYPTION: ssl
      MAIL_FROM_ADDRESS: perproject2@gmail.com
      MAIL_FROM_NAME: "C贸digo de confirmaci贸n"
    depends_on:
      - db
    networks:
      - epayco-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: epayco_client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - epayco-net

  db:
    image: mysql:8.0
    container_name: epayco_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: epayco_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - epayco-net

networks:
  epayco-net:
    driver: bridge

volumes:
  db-data:
    driver: local